CREATE TABLE "agencies" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agency_name" varchar,
  "owner_name" varchar,
  "contact" varchar,
  "email" varchar,
  "description" text,
  "website" varchar,
  "location" varchar,
  "profile_image" text,
  "status" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "social_medias" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agency_id" bigint,
  "platform" varchar,
  "url" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agency_id" bigint,
  "full_name" varchar,
  "email" varchar,
  "password" text,
  "role" varchar,
  "phone" varchar,
  "profile_image" text,
  "is_active" boolean,
  "last_login" timestamp,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "project_requests" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agency_id" bigint,
  "client_id" bigint,
  "title" varchar,
  "description" text,
  "category" varchar,
  "budget_min" decimal,
  "budget_max" decimal,
  "deadline" date,
  "attachment_url" text,
  "status" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "projects" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agency_id" bigint,
  "project_request_id" bigint,
  "client_id" bigint,
  "title" varchar,
  "description" text,
  "budget" decimal,
  "progress" int,
  "current_phase" varchar,
  "start_date" date,
  "end_date" date,
  "status" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "project_members" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" bigint,
  "developer_id" bigint,
  "assigned_at" timestamp
);

CREATE TABLE "milestones" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" bigint,
  "title" varchar,
  "description" text,
  "progress" int,
  "due_date" date,
  "status" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "tasks" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agency_id" bigint,
  "project_id" bigint,
  "milestone_id" bigint,
  "assigned_to" bigint,
  "title" varchar,
  "description" text,
  "priority" varchar,
  "status" varchar,
  "estimated_hours" decimal,
  "due_date" date,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "subtasks" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_id" bigint,
  "title" varchar,
  "status" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "time_logs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_id" bigint,
  "developer_id" bigint,
  "started_at" timestamp,
  "ended_at" timestamp,
  "total_hours" decimal,
  "created_at" timestamp
);

CREATE TABLE "bug_reports" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" bigint,
  "task_id" bigint,
  "reported_by" bigint,
  "assigned_to" bigint,
  "title" varchar,
  "description" text,
  "severity" varchar,
  "status" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "comments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agency_id" bigint,
  "project_id" bigint,
  "task_id" bigint,
  "user_id" bigint,
  "comment" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "files" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agency_id" bigint,
  "project_id" bigint,
  "uploaded_by" bigint,
  "file_name" varchar,
  "file_url" text,
  "file_size" bigint,
  "mime_type" varchar,
  "created_at" timestamp
);

CREATE TABLE "invoices" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agency_id" bigint,
  "project_id" bigint,
  "client_id" bigint,
  "invoice_number" varchar,
  "amount" decimal,
  "status" varchar,
  "due_date" date,
  "paid_at" timestamp,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "notifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agency_id" bigint,
  "user_id" bigint,
  "title" varchar,
  "message" text,
  "is_read" boolean,
  "created_at" timestamp
);

CREATE TABLE "activity_logs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agency_id" bigint,
  "user_id" bigint,
  "action" varchar,
  "entity_type" varchar,
  "entity_id" bigint,
  "ip_address" varchar,
  "created_at" timestamp
);

ALTER TABLE "social_medias" ADD FOREIGN KEY ("agency_id") REFERENCES "agencies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "users" ADD FOREIGN KEY ("agency_id") REFERENCES "agencies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "project_requests" ADD FOREIGN KEY ("agency_id") REFERENCES "agencies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "project_requests" ADD FOREIGN KEY ("client_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "projects" ADD FOREIGN KEY ("agency_id") REFERENCES "agencies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "projects" ADD FOREIGN KEY ("project_request_id") REFERENCES "project_requests" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "projects" ADD FOREIGN KEY ("client_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "project_members" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "project_members" ADD FOREIGN KEY ("developer_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "milestones" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tasks" ADD FOREIGN KEY ("agency_id") REFERENCES "agencies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tasks" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tasks" ADD FOREIGN KEY ("milestone_id") REFERENCES "milestones" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tasks" ADD FOREIGN KEY ("assigned_to") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "subtasks" ADD FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "time_logs" ADD FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "time_logs" ADD FOREIGN KEY ("developer_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bug_reports" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bug_reports" ADD FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bug_reports" ADD FOREIGN KEY ("reported_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bug_reports" ADD FOREIGN KEY ("assigned_to") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments" ADD FOREIGN KEY ("agency_id") REFERENCES "agencies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments" ADD FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "files" ADD FOREIGN KEY ("agency_id") REFERENCES "agencies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "files" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "files" ADD FOREIGN KEY ("uploaded_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "invoices" ADD FOREIGN KEY ("agency_id") REFERENCES "agencies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "invoices" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "invoices" ADD FOREIGN KEY ("client_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("agency_id") REFERENCES "agencies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "activity_logs" ADD FOREIGN KEY ("agency_id") REFERENCES "agencies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "activity_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

CREATE TABLE "refresh_tokens" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "token" varchar UNIQUE NOT NULL,
  "expires_at" timestamp NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "password_reset_tokens" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "token" varchar UNIQUE NOT NULL,
  "expires_at" timestamp NOT NULL,
  "created_at" timestamp
);

ALTER TABLE "refresh_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "password_reset_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
